version: "3.8"

services:

  inve24_nginx:
    image: inve24_nginx:local
    container_name: inve24_nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile.local
    restart: unless-stopped
    depends_on:
      - inve24_db
      - inve24_api
    ports:
      - 80:80
    networks:
      - inve24_network

  inve24_api:
    image: inve24_api:local
    container_name: inve24_api
    build:
      context: .
      dockerfile: Dockerfile.local
    depends_on:
      - mysql_db
    env_file:
      - .env.local
    networks:
      - inve24_network

  inve24_db:
    image: mysql:8.0
    container_name: inve24_db
    restart: always
    volumes:
      - inve24_db_data:/var/lib/mysql
    ports:
      - 3307:3307
    env_file:
      - .env.local
    networks:
      - inve24_network

volumes:
  inve24_db_data:
    driver: local

networks:
  inve24_network:
    driver: bridge
