version: "3.8"

services:

  inve24_nginx:
    image: okonomiyakki/inve24_nginx:prod
    container_name: inve24_nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - inve24_db
      - inve24_api
    ports:
      - 80:80
      - 443:443
    networks:
      - inve24_network

  inve24_api:
    image: okonomiyakki/inve24_api:prod
    container_name: inve24_api
    build:
      context: .
      dockerfile: Dockerfile.prod
    depends_on:
      - mysql_db
    env_file:
      - .env.prod
    networks:
      - inve24_network

  inve24_db:
    image: mysql:8.0
    container_name: inve24_db
    restart: always
    volumes:
      - inve24_db_data:/var/lib/mysql
    ports:
      - 3306:3306
    env_file:
      - .env.prod
    networks:
      - inve24_network

volumes:
  inve24_db_data:
    driver: local

networks:
  inve24_network:
    driver: bridge
