export const EMAIL_CERT_CODE_REDIS_NAMESPACE = 'EMAIL_CERT_CODE_REDIS_NAMESPACE';
export const REFRESH_TOKEN_REDIS_NAMESPACE = 'REFRESH_TOKEN_REDIS_NAMESPACE';
export const SUMMONER_REDIS_NAMESPACE = 'SUMMONER_REDIS_NAMESPACE';
export const SOCKET_CLIENT_REDIS_NAMESPACE = 'SOCKET_CLIENT_REDIS_NAMESPACE';
