export const EMAIL_CERT_CODE_REDIS_NAMESPACE = 'EMAIL_CERT_CODE_REDIS_NAMESPACE';
export const REFRESH_TOKEN_REDIS_NAMESPACE = 'REFRESH_TOKEN_REDIS_NAMESPACE';
export const SUMMONER_REDIS_NAMESPACE = 'SUMMONER_REDIS_NAMESPACE';
