export const SERVER_CONFIG_TOKEN = 'SERVER_CONFIG_TOKEN';
export const DATABASE_CONFIG_TOKEN = 'DATABASE_CONFIG_TOKEN';
export const JWT_CONFIG_TOKEN = 'JWT_CONFIG_TOKEN';
export const BCRYPT_CONFIG_TOKEN = 'BCRYPT_CONFIG_TOKEN';
export const MAIL_CONFIG_TOKEN = 'MAIL_CONFIG_TOKEN';
export const REDIS_CONFIG_TOKEN = 'REDIS_CONFIG_TOKEN';
